-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL custorders_schema_output.txt

--student id: 35501308
--student name: Bharath Arun Gandhimani

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-10 20:30:39 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE CUSTOMER CASCADE CONSTRAINTS 
;

DROP TABLE ORDERLINE CASCADE CONSTRAINTS 
;

DROP TABLE ORDERS CASCADE CONSTRAINTS 
;

DROP TABLE PROD_CATEGORY CASCADE CONSTRAINTS 
;

DROP TABLE PRODUCT CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CUSTOMER 
    ( 
     cust_no      NUMBER (7)  NOT NULL , 
     cust_name    CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     cust_address CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     cust_phone   NUMBER (10) , 
     cust_level   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT chk_custlevel 
    CHECK (cust_level IN (B, G, S)) 
;

COMMENT ON COLUMN CUSTOMER.cust_no IS 'Customer Number' 
;

COMMENT ON COLUMN CUSTOMER.cust_name IS 'Customer Name' 
;

COMMENT ON COLUMN CUSTOMER.cust_address IS 'Customer Address' 
;

COMMENT ON COLUMN CUSTOMER.cust_phone IS 'Customer Phone Number' 
;

COMMENT ON COLUMN CUSTOMER.cust_level IS 'Customer Level' 
;

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( cust_no ) ;

CREATE TABLE ORDERLINE 
    ( 
     order_no      NUMBER (7)  NOT NULL , 
     prod_no       NUMBER (7)  NOT NULL , 
     ol_qtyordered NUMBER  NOT NULL , 
     ol_lineprice  NUMBER  NOT NULL 
    ) 
;

COMMENT ON COLUMN ORDERLINE.prod_no IS 'Product Number' 
;

COMMENT ON COLUMN ORDERLINE.ol_qtyordered IS 'Quantity Ordered' 
;

COMMENT ON COLUMN ORDERLINE.ol_lineprice IS 'Line Price' 
;

ALTER TABLE ORDERLINE 
    ADD CONSTRAINT ORDERLINE_PK PRIMARY KEY ( order_no, prod_no ) ;

CREATE TABLE ORDERS 
    ( 
     order_no   NUMBER (7)  NOT NULL , 
     order_date DATE  NOT NULL , 
     cust_no    NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ORDERS.order_date IS 'Order Date' 
;

COMMENT ON COLUMN ORDERS.cust_no IS 'Customer Number' 
;

ALTER TABLE ORDERS 
    ADD CONSTRAINT ORDERS_PK PRIMARY KEY ( order_no ) ;

CREATE TABLE PROD_CATEGORY 
    ( 
     pcat_id   NUMBER  NOT NULL , 
     pcat_name CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL 
    ) 
;

COMMENT ON COLUMN PROD_CATEGORY.pcat_id IS 'Product Category ID' 
;

COMMENT ON COLUMN PROD_CATEGORY.pcat_name IS 'Procuct Category Name' 
;

ALTER TABLE PROD_CATEGORY 
    ADD CONSTRAINT PROD_CATEGORY_PK PRIMARY KEY ( pcat_id ) ;

CREATE TABLE PRODUCT 
    ( 
     prod_no        NUMBER (7)  NOT NULL , 
     prod_desc      CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     prod_unitprice NUMBER  NOT NULL , 
     prid_category  CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     pcat_id        NUMBER  NOT NULL 
    ) 
;

COMMENT ON COLUMN PRODUCT.prod_no IS 'Product Number' 
;

COMMENT ON COLUMN PRODUCT.prod_desc IS 'Product Description' 
;

COMMENT ON COLUMN PRODUCT.prod_unitprice IS 'Product Unit Price' 
;

COMMENT ON COLUMN PRODUCT.prid_category IS 'Product Category' 
;

COMMENT ON COLUMN PRODUCT.pcat_id IS 'Product Category ID' 
;

ALTER TABLE PRODUCT 
    ADD CONSTRAINT PRODUCT_PK PRIMARY KEY ( prod_no ) ;

ALTER TABLE PRODUCT 
    ADD CONSTRAINT "category-product_fk" FOREIGN KEY 
    ( 
     pcat_id
    ) 
    REFERENCES PROD_CATEGORY 
    ( 
     pcat_id
    ) 
;

ALTER TABLE ORDERS 
    ADD CONSTRAINT cust_order_fk FOREIGN KEY 
    ( 
     cust_no
    ) 
    REFERENCES CUSTOMER 
    ( 
     cust_no
    ) 
;

ALTER TABLE ORDERLINE 
    ADD CONSTRAINT orders_orderline_fk FOREIGN KEY 
    ( 
     order_no
    ) 
    REFERENCES ORDERS 
    ( 
     order_no
    ) 
;

ALTER TABLE ORDERLINE 
    ADD CONSTRAINT "products-orderline_fk" FOREIGN KEY 
    ( 
     prod_no
    ) 
    REFERENCES PRODUCT 
    ( 
     prod_no
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 5

SPOOL off
set echo off