-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-29 15:26:35 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Capture run of script in file called oo_schema_output.txt
set echo on
SPOOL oo_schema_output.txt

--student id: 35501308
--student name: Bharath Arun Gandhimani

DROP TABLE BOOKING CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE BOOKING 
    ( 
     booking_no   NUMBER (7)  NOT NULL , 
     cruise_id    NUMBER (7)  NOT NULL , 
     cabin_no     NUMBER (7)  NOT NULL , 
     pass_id      NUMBER (7)  NOT NULL , 
     booking_date DATE  NOT NULL , 
     booking_time VARCHAR2 (25)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BOOKING.booking_no IS 'Booking Number (Surrogate PK)' 
;

COMMENT ON COLUMN BOOKING.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN BOOKING.cabin_no IS 'Cabin Number' 
;

COMMENT ON COLUMN BOOKING.pass_id IS 'Passenger ID' 
;

COMMENT ON COLUMN BOOKING.booking_date IS 'Booking Date' 
;

COMMENT ON COLUMN BOOKING.booking_time IS 'Booking Time' 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( booking_no ) ;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_NK UNIQUE ( cruise_id , cabin_no , pass_id ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no          NUMBER (7)  NOT NULL , 
     ship_code         NUMBER (7)  NOT NULL , 
     sleeping_capacity NUMBER (25)  NOT NULL , 
     cabin_class       VARCHAR2 (25)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabin_class 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'Cabin Number' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'Ship Code' 
;

COMMENT ON COLUMN CABIN.sleeping_capacity IS 'Sleeping Capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Cabin Class' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (25)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'Country Code' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'Country Name' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id       NUMBER (7)  NOT NULL , 
     ship_code       NUMBER (7)  NOT NULL , 
     cruise_name     VARCHAR2 (25)  NOT NULL , 
     cruise_desc     VARCHAR2 (50)  NOT NULL , 
     dept_date       DATE  NOT NULL , 
     dept_time       VARCHAR2 (25)  NOT NULL , 
     cost_per_person NUMBER (15)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'Ship Code' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Cruise Name' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Cruise Description' 
;

COMMENT ON COLUMN CRUISE.dept_date IS 'Departure Dare' 
;

COMMENT ON COLUMN CRUISE.dept_time IS 'Deptarture Time' 
;

COMMENT ON COLUMN CRUISE.cost_per_person IS 'Cost per Person' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE ITINERARY 
    ( 
     date_time         VARCHAR2 (25)  NOT NULL , 
     cruise_id         NUMBER (7)  NOT NULL , 
     port_code         CHAR (5)  NOT NULL , 
     departure_arrival VARCHAR2 (10)  NOT NULL , 
     itinerary_no      NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT chk_depart_arrival 
    CHECK (departure_arrival IN ('Arrival', 'Departure')) 
;

COMMENT ON COLUMN ITINERARY.date_time IS 'Itinerary Date Time' 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'Cruise ID' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'Port Code' 
;

COMMENT ON COLUMN ITINERARY.departure_arrival IS 'Departure or Arrival' 
;

COMMENT ON COLUMN ITINERARY.itinerary_no IS 'Itinerary Number (Surrogate Key)' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_PK PRIMARY KEY ( date_time ) ;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_NK UNIQUE ( cruise_id , port_code , date_time ) ;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_NKv2 UNIQUE ( date_time , cruise_id , port_code ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id  NUMBER (7)  NOT NULL , 
     company_name VARCHAR2 (25)  NOT NULL , 
     ceo_name     VARCHAR2 (25)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'Operator ID' 
;

COMMENT ON COLUMN OPERATOR.company_name IS 'Company Name' 
;

COMMENT ON COLUMN OPERATOR.ceo_name IS 'CEO Name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     pass_id       NUMBER (7)  NOT NULL , 
     guardian_id   NUMBER (7) , 
     pass_fname    VARCHAR2 (25) , 
     pass_lname    VARCHAR2 (25) , 
     pass_gender   VARCHAR2 (10)  NOT NULL , 
     pass_dob      DATE  NOT NULL , 
     pass_street   VARCHAR2 (50)  NOT NULL , 
     pass_town     VARCHAR2 (25)  NOT NULL , 
     pass_passcode VARCHAR2 (25)  NOT NULL , 
     pass_country  VARCHAR2 (25)  NOT NULL , 
     pass_phone_no NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT chk_passenger_gender 
    CHECK (pass_gender IN ('F', 'M')) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT chk_phone_no 
    CHECK ((pass_dob <= SYSDATE - INTERVAL '18' YEAR AND pass_phone_no IS NOT NULL) OR (pass_dob > SYSDATE - INTERVAL '18' YEAR AND pass_phone_no IS NULL)) 
;

COMMENT ON COLUMN PASSENGER.pass_id IS 'Passenger ID' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'Passenger ID' 
;

COMMENT ON COLUMN PASSENGER.pass_fname IS 'Passenger First Name' 
;

COMMENT ON COLUMN PASSENGER.pass_lname IS 'Passenger Last Name' 
;

COMMENT ON COLUMN PASSENGER.pass_gender IS 'Passenger Gender' 
;

COMMENT ON COLUMN PASSENGER.pass_dob IS 'Passenger Date of Birth' 
;

COMMENT ON COLUMN PASSENGER.pass_street IS 'Passenger Street' 
;

COMMENT ON COLUMN PASSENGER.pass_town IS 'Passenger Town' 
;

COMMENT ON COLUMN PASSENGER.pass_passcode IS 'Passenger Passcode' 
;

COMMENT ON COLUMN PASSENGER.pass_country IS 'Passenger Country' 
;

COMMENT ON COLUMN PASSENGER.pass_phone_no IS 'Passenger Phone Number' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( pass_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      CHAR (5)  NOT NULL , 
     country_code   CHAR (3)  NOT NULL , 
     port_name      VARCHAR2 (10)  NOT NULL , 
     port_latitude  VARCHAR2 (20)  NOT NULL , 
     port_longitude VARCHAR2 (25)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'Port Code' 
;

COMMENT ON COLUMN PORT.country_code IS 'Country Code' 
;

COMMENT ON COLUMN PORT.port_name IS 'Port Name' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'Port Latitude' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'Port Longitude' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code       NUMBER (7)  NOT NULL , 
     reg_country     CHAR (3)  NOT NULL , 
     operator_id     NUMBER (7)  NOT NULL , 
     ship_name       VARCHAR2 (25)  NOT NULL , 
     commission_date DATE  NOT NULL , 
     tonnage         NUMBER (10)  NOT NULL , 
     max_guest_cap   NUMBER (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'Ship Code' 
;

COMMENT ON COLUMN SHIP.reg_country IS 'Country Code' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'Operator ID' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Ship Name' 
;

COMMENT ON COLUMN SHIP.commission_date IS 'Commission Date' 
;

COMMENT ON COLUMN SHIP.tonnage IS 'Tonnage' 
;

COMMENT ON COLUMN SHIP.max_guest_cap IS 'Maximum Guest Capacity' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE BOOKING 
    ADD CONSTRAINT "cabin-booking_fk" FOREIGN KEY 
    ( 
     cabin_no
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT "country-port_fk" FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT "country-ship_fk" FOREIGN KEY 
    ( 
     reg_country
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT "cruise-booking_fk" FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT "cruise-itinerary_fk" FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT "operator-ship_fk" FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT "passenger-booking_fk" FOREIGN KEY 
    ( 
     pass_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pass_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT "passenger-guardian_fk" FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     pass_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT "port-itinerary_fk" FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT "ship-cabin_fk" FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT "ship-cruise_fk" FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
SPOOL off
set echo off