-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-14 22:25:24 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL prop_rental_schema_output.txt

--student id: 35501308
--student name: Bharath Arun Gandhimani

DROP TABLE DAMAGE CASCADE CONSTRAINTS 
;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS 
;

DROP TABLE OWNER CASCADE CONSTRAINTS 
;

DROP TABLE PAYMENT CASCADE CONSTRAINTS 
;

DROP TABLE PAYMETHOD CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY CASCADE CONSTRAINTS 
;

DROP TABLE RENT CASCADE CONSTRAINTS 
;

DROP TABLE TENANT CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE DAMAGE 
    ( 
     dam_no            NUMBER (7)  NOT NULL , 
     dam_datetime      DATE  NOT NULL , 
     rent_agreement_no NUMBER (7)  NOT NULL , 
     dam_type          CHAR (25)  NOT NULL , 
     dam_cost          NUMBER (50)  NOT NULL , 
     pay_no            NUMBER (7) 
    ) 
;

COMMENT ON COLUMN DAMAGE.dam_no IS 'Damage Number' 
;

COMMENT ON COLUMN DAMAGE.dam_datetime IS 'Damage Date Time' 
;

COMMENT ON COLUMN DAMAGE.rent_agreement_no IS 'Rent Agreement Number' 
;

COMMENT ON COLUMN DAMAGE.dam_type IS 'Damage Type' 
;

COMMENT ON COLUMN DAMAGE.dam_cost IS 'Damage Cost' 
;

COMMENT ON COLUMN DAMAGE.pay_no IS 'Payment Number' 
;
CREATE UNIQUE INDEX DAMAGE__IDX ON DAMAGE 
    ( 
     pay_no ASC 
    ) 
;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT DAMAGE_PK PRIMARY KEY ( dam_no ) ;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT dam_datetime UNIQUE ( dam_datetime ) ;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT Key_3 UNIQUE ( rent_agreement_no ) ;

CREATE TABLE MAINTENANCE 
    ( 
     maint_datetime DATE  NOT NULL , 
     maint_desc     CHAR (50)  NOT NULL , 
     maint_cost     NUMBER (50)  NOT NULL , 
     prop_no        NUMBER  NOT NULL 
    ) 
;

COMMENT ON COLUMN MAINTENANCE.maint_datetime IS 'Maintenance Date Time' 
;

COMMENT ON COLUMN MAINTENANCE.maint_desc IS 'Maintenance Description' 
;

COMMENT ON COLUMN MAINTENANCE.maint_cost IS 'Maintenance Cost' 
;

COMMENT ON COLUMN MAINTENANCE.prop_no IS 'Property Number' 
;

ALTER TABLE MAINTENANCE 
    ADD CONSTRAINT MAINTENANCE_PK PRIMARY KEY ( maint_datetime, prop_no ) ;

CREATE TABLE OWNER 
    ( 
     owner_no      NUMBER (7)  NOT NULL , 
     owner_givname CHAR (25) , 
     owner_famname CHAR 
--  WARNING: CHAR size not specified 
                    , 
     owner_name    CHAR (25)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OWNER.owner_no IS 'Order Number' 
;

COMMENT ON COLUMN OWNER.owner_givname IS 'Owner Given Name' 
;

COMMENT ON COLUMN OWNER.owner_famname IS 'Owner Family Name' 
;

COMMENT ON COLUMN OWNER.owner_name IS 'Owner Name' 
;

ALTER TABLE OWNER 
    ADD CONSTRAINT OWNER_PK PRIMARY KEY ( owner_no ) ;

CREATE TABLE PAYMENT 
    ( 
     pay_no            NUMBER (7)  NOT NULL , 
     pay_date          DATE  NOT NULL , 
     pay_type          CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     pay_amount        NUMBER (50)  NOT NULL , 
     pay_paidby        NUMBER (7)  NOT NULL , 
     rent_agreement_no NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT chk_pay_type 
    CHECK (pay_type IN ('D', 'P', 'R')) 
;

COMMENT ON COLUMN PAYMENT.pay_no IS 'Payment Number' 
;

COMMENT ON COLUMN PAYMENT.pay_date IS 'Payment Date' 
;

COMMENT ON COLUMN PAYMENT.pay_type IS 'Payment Type' 
;

COMMENT ON COLUMN PAYMENT.pay_amount IS 'Payment Amount' 
;

COMMENT ON COLUMN PAYMENT.pay_paidby IS 'Payment Method ID' 
;

COMMENT ON COLUMN PAYMENT.rent_agreement_no IS 'Rent Agreement Number' 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( pay_no ) ;

CREATE TABLE PAYMETHOD 
    ( 
     paymethod_id   NUMBER (7)  NOT NULL , 
     paymethod_name CHAR (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PAYMETHOD.paymethod_id IS 'Payment Method ID' 
;

COMMENT ON COLUMN PAYMETHOD.paymethod_name IS 'Payment Method Name' 
;

ALTER TABLE PAYMETHOD 
    ADD CONSTRAINT PAYMETHOD_PK PRIMARY KEY ( paymethod_id ) ;

CREATE TABLE PROPERTY 
    ( 
     prop_no      NUMBER  NOT NULL , 
     prop_address CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     prop_value   NUMBER  NOT NULL , 
     owner_no     NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PROPERTY.prop_no IS 'Property Number' 
;

COMMENT ON COLUMN PROPERTY.prop_address IS 'Property Address' 
;

COMMENT ON COLUMN PROPERTY.prop_value IS 'Property Value' 
;

COMMENT ON COLUMN PROPERTY.owner_no IS 'Order Number' 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT PROPERTY_PK PRIMARY KEY ( prop_no ) ;

CREATE TABLE RENT 
    ( 
     rent_agreement_no NUMBER (7)  NOT NULL , 
     rent_lease_start  DATE  NOT NULL , 
     rent_weekly_rate  NUMBER (25)  NOT NULL , 
     rent_bond         NUMBER (10)  NOT NULL , 
     rent_lease_period NUMBER  NOT NULL , 
     prop_no           NUMBER  NOT NULL , 
     tenant_no         NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN RENT.rent_agreement_no IS 'Rent Agreement Number' 
;

COMMENT ON COLUMN RENT.rent_lease_start IS 'Rent Lease Start Date' 
;

COMMENT ON COLUMN RENT.rent_bond IS 'Rent Bond' 
;

COMMENT ON COLUMN RENT.rent_lease_period IS 'Rent Lease Period' 
;

COMMENT ON COLUMN RENT.prop_no IS 'Property Number' 
;

COMMENT ON COLUMN RENT.tenant_no IS 'Tenant Number' 
;

ALTER TABLE RENT 
    ADD CONSTRAINT RENT_PK PRIMARY KEY ( rent_agreement_no ) ;

ALTER TABLE RENT 
    ADD CONSTRAINT rent_lease_start UNIQUE ( rent_lease_start ) ;

ALTER TABLE RENT 
    ADD CONSTRAINT Key_3v1 UNIQUE ( prop_no ) ;

CREATE TABLE TENANT 
    ( 
     tenant_no      NUMBER (7)  NOT NULL , 
     tenant_givname CHAR 
--  WARNING: CHAR size not specified 
                    , 
     tenant_famname CHAR 
--  WARNING: CHAR size not specified 
                    , 
     tenant_address CHAR (50)  NOT NULL , 
     tenant_phone   NUMBER  NOT NULL 
    ) 
;

COMMENT ON COLUMN TENANT.tenant_no IS 'Tenant Number' 
;

COMMENT ON COLUMN TENANT.tenant_givname IS 'Tenant Given Name' 
;

COMMENT ON COLUMN TENANT.tenant_famname IS 'Tenant Family Name' 
;

COMMENT ON COLUMN TENANT.tenant_address IS 'Tenant Address' 
;

COMMENT ON COLUMN TENANT.tenant_phone IS 'Tenant Phone' 
;

ALTER TABLE TENANT 
    ADD CONSTRAINT TENANT_PK PRIMARY KEY ( tenant_no ) ;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT damage_payment_fk FOREIGN KEY 
    ( 
     pay_no
    ) 
    REFERENCES PAYMENT 
    ( 
     pay_no
    ) 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT "owner-property_fk" FOREIGN KEY 
    ( 
     owner_no
    ) 
    REFERENCES OWNER 
    ( 
     owner_no
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT "paymethod-payment_fk" FOREIGN KEY 
    ( 
     pay_paidby
    ) 
    REFERENCES PAYMETHOD 
    ( 
     paymethod_id
    ) 
;

ALTER TABLE RENT 
    ADD CONSTRAINT property_rent_fk FOREIGN KEY 
    ( 
     prop_no
    ) 
    REFERENCES PROPERTY 
    ( 
     prop_no
    ) 
;

ALTER TABLE MAINTENANCE 
    ADD CONSTRAINT "property-maintenance_fk" FOREIGN KEY 
    ( 
     prop_no
    ) 
    REFERENCES PROPERTY 
    ( 
     prop_no
    ) 
;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT "rent-damage_fk" FOREIGN KEY 
    ( 
     rent_agreement_no
    ) 
    REFERENCES RENT 
    ( 
     rent_agreement_no
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT "rent-payent_fk" FOREIGN KEY 
    ( 
     rent_agreement_no
    ) 
    REFERENCES RENT 
    ( 
     rent_agreement_no
    ) 
;

ALTER TABLE RENT 
    ADD CONSTRAINT "tenant-rent_fk" FOREIGN KEY 
    ( 
     tenant_no
    ) 
    REFERENCES TENANT 
    ( 
     tenant_no
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 5
SPOOL off
set echo off